#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using MyERP.DataAccess;

namespace MyERP.DataAccess	
{
	public partial class Client : IDataErrorInfo, INotifyPropertyChanging, INotifyPropertyChanged
	{
		private Guid _clientId;
		public virtual Guid ClientId
		{
			get
			{
				return this._clientId;
			}
			set
			{
				if(this._clientId != value)
				{
					this.OnPropertyChanging("ClientId");
					this._clientId = value;
					this.OnPropertyChanged("ClientId");
				}
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				if(this._name != value)
				{
					this.OnPropertyChanging("Name");
					this._name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}
		
		private long _version;
		public virtual long Version
		{
			get
			{
				return this._version;
			}
			set
			{
				if(this._version != value)
				{
					this.OnPropertyChanging("Version");
					this._version = value;
					this.OnPropertyChanged("Version");
				}
			}
		}
		
		private bool _isActivated;
		public virtual bool IsActivated
		{
			get
			{
				return this._isActivated;
			}
			set
			{
				if(this._isActivated != value)
				{
					this.OnPropertyChanging("IsActivated");
					this._isActivated = value;
					this.OnPropertyChanged("IsActivated");
				}
			}
		}
		
		private Guid _recCreatedById;
		public virtual Guid RecCreatedById
		{
			get
			{
				return this._recCreatedById;
			}
			set
			{
				if(this._recCreatedById != value)
				{
					this.OnPropertyChanging("RecCreatedById");
					this._recCreatedById = value;
					this.OnPropertyChanged("RecCreatedById");
				}
			}
		}
		
		private DateTime _recCreated;
		public virtual DateTime RecCreated
		{
			get
			{
				return this._recCreated;
			}
			set
			{
				if(this._recCreated != value)
				{
					this.OnPropertyChanging("RecCreated");
					this._recCreated = value;
					this.OnPropertyChanged("RecCreated");
				}
			}
		}
		
		private string _cultureId;
		public virtual string CultureId
		{
			get
			{
				return this._cultureId;
			}
			set
			{
				if(this._cultureId != value)
				{
					this.OnPropertyChanging("CultureId");
					this._cultureId = value;
					this.OnPropertyChanged("CultureId");
				}
			}
		}
		
		private string _culuteUIId;
		public virtual string CuluteUIId
		{
			get
			{
				return this._culuteUIId;
			}
			set
			{
				if(this._culuteUIId != value)
				{
					this.OnPropertyChanging("CuluteUIId");
					this._culuteUIId = value;
					this.OnPropertyChanged("CuluteUIId");
				}
			}
		}
		
		private User _user;
		public virtual User RecCreatedByUser
		{
			get
			{
				return this._user;
			}
			set
			{
				if(this._user != value)
				{
					this.OnPropertyChanging("RecCreatedByUser");
					this._user = value;
					this.OnPropertyChanged("RecCreatedByUser");
				}
			}
		}
		
		private IList<Organization> _organization = new List<Organization>();
		public virtual IList<Organization> Organizations
		{
			get
			{
				return this._organization;
			}
		}
		
		#region IDataErrorInfo members
		
		private string error = string.Empty;
		public string Error
		{
			get
			{
				return this.error;
			}
		}
		
		public string this[string propertyName]
		{
			get
			{
				this.ValidatePropertyInternal(propertyName, ref this.error);
		
				return this.error;
			}
		}
		
		protected virtual void ValidatePropertyInternal(string propertyName, ref string error)
		{
		    this.ValidateProperty(propertyName, ref error);
		}
		
		// Please implement this method in a partial class in order to provide the error message depending on each of the properties.
		partial void ValidateProperty(string propertyName, ref string error);
		
		#endregion
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
