#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MyERP.DataAccess;

namespace MyERP.DataAccess	
{
	[Table("currency_convert_rate", UpdateSchema = true)]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Version)]
	public partial class CurrencyConvertRate
	{
		private Guid _id;
		[Column("id", OpenAccessType = OpenAccessType.Guid, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "uuid", Converter = "OpenAccessRuntime.Data.GuidConverter")]
		[Storage("_id")]
		public virtual Guid Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime _recCreated;
		[Column("rec_created", OpenAccessType = OpenAccessType.DateTime, Length = 0, Scale = 0, SqlType = "timestamp", Converter = "OpenAccessRuntime.Data.PostgresTimestampTZConverter")]
		[Storage("_recCreated")]
		public virtual DateTime RecCreated
		{
			get
			{
				return this._recCreated;
			}
			set
			{
				this._recCreated = value;
			}
		}
		
		private Guid _recCreatedBy;
		[Column("rec_created_by", OpenAccessType = OpenAccessType.Guid, Length = 0, Scale = 0, SqlType = "uuid", Converter = "OpenAccessRuntime.Data.GuidConverter")]
		[Storage("_recCreatedBy")]
		public virtual Guid RecCreatedBy
		{
			get
			{
				return this._recCreatedBy;
			}
			set
			{
				this._recCreatedBy = value;
			}
		}
		
		private DateTime _recModified;
		[Column("rec_modified", OpenAccessType = OpenAccessType.DateTime, Length = 0, Scale = 0, SqlType = "timestamp", Converter = "OpenAccessRuntime.Data.PostgresTimestampTZConverter")]
		[Storage("_recModified")]
		public virtual DateTime RecModified
		{
			get
			{
				return this._recModified;
			}
			set
			{
				this._recModified = value;
			}
		}
		
		private Guid _recModifiedBy;
		[Column("rec_modified_by", OpenAccessType = OpenAccessType.Guid, Length = 0, Scale = 0, SqlType = "uuid", Converter = "OpenAccessRuntime.Data.GuidConverter")]
		[Storage("_recModifiedBy")]
		public virtual Guid RecModifiedBy
		{
			get
			{
				return this._recModifiedBy;
			}
			set
			{
				this._recModifiedBy = value;
			}
		}
		
		private Guid _clientId;
		[Column("client_id", OpenAccessType = OpenAccessType.Guid, Length = 0, Scale = 0, SqlType = "uuid", Converter = "OpenAccessRuntime.Data.GuidConverter")]
		[Storage("_clientId")]
		public virtual Guid ClientId
		{
			get
			{
				return this._clientId;
			}
			set
			{
				this._clientId = value;
			}
		}
		
		private Guid _organizationId;
		[Column("organization_id", OpenAccessType = OpenAccessType.Guid, Length = 0, Scale = 0, SqlType = "uuid", Converter = "OpenAccessRuntime.Data.GuidConverter")]
		[Storage("_organizationId")]
		public virtual Guid OrganizationId
		{
			get
			{
				return this._organizationId;
			}
			set
			{
				this._organizationId = value;
			}
		}
		
		private long _version;
		[Column("version", OpenAccessType = OpenAccessType.Int64, IsVersion = true, Length = 0, Scale = 0, SqlType = "int8", Converter = "OpenAccessRuntime.Data.BigIntConverter")]
		[Storage("_version")]
		public virtual long Version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
		
		private Guid _currencyId;
		[Column("currency_id", OpenAccessType = OpenAccessType.Guid, Length = 0, Scale = 0, SqlType = "uuid", Converter = "OpenAccessRuntime.Data.GuidConverter")]
		[Storage("_currencyId")]
		public virtual Guid CurrencyId
		{
			get
			{
				return this._currencyId;
			}
			set
			{
				this._currencyId = value;
			}
		}
		
		private Guid _currencyIdTo;
		[Column("currency_id_to", OpenAccessType = OpenAccessType.Guid, Length = 0, Scale = 0, SqlType = "uuid", Converter = "OpenAccessRuntime.Data.GuidConverter")]
		[Storage("_currencyIdTo")]
		public virtual Guid CurrencyIdTo
		{
			get
			{
				return this._currencyIdTo;
			}
			set
			{
				this._currencyIdTo = value;
			}
		}
		
		private DateTime _validFrom;
		[Column("valid_from", OpenAccessType = OpenAccessType.DateTime, Length = 0, Scale = 0, SqlType = "date", Converter = "OpenAccessRuntime.Data.PostgresTimestampTZConverter")]
		[Storage("_validFrom")]
		public virtual DateTime ValidFrom
		{
			get
			{
				return this._validFrom;
			}
			set
			{
				this._validFrom = value;
			}
		}
		
		private DateTime _validTo;
		[Column("valid_to", OpenAccessType = OpenAccessType.DateTime, Length = 0, Scale = 0, SqlType = "date", Converter = "OpenAccessRuntime.Data.PostgresTimestampTZConverter")]
		[Storage("_validTo")]
		public virtual DateTime ValidTo
		{
			get
			{
				return this._validTo;
			}
			set
			{
				this._validTo = value;
			}
		}
		
		private int _multiplyRate;
		[Column("multiply_rate", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int4", Converter = "OpenAccessRuntime.Data.IntConverter")]
		[Storage("_multiplyRate")]
		public virtual int MultiplyRate
		{
			get
			{
				return this._multiplyRate;
			}
			set
			{
				this._multiplyRate = value;
			}
		}
		
		private int _divideRate;
		[Column("divide_rate", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int4", Converter = "OpenAccessRuntime.Data.IntConverter")]
		[Storage("_divideRate")]
		public virtual int DivideRate
		{
			get
			{
				return this._divideRate;
			}
			set
			{
				this._divideRate = value;
			}
		}
		
		private byte _status;
		[Column("status", OpenAccessType = OpenAccessType.Int16, Length = 0, Scale = 0, SqlType = "int2", Converter = "OpenAccessRuntime.Data.TinyInt2UByteConverter")]
		[Storage("_status")]
		public virtual byte Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private byte _conversionRateType;
		[Column("conversion_rate_type", OpenAccessType = OpenAccessType.Int16, Length = 0, Scale = 0, SqlType = "int2", Converter = "OpenAccessRuntime.Data.TinyInt2UByteConverter")]
		[Storage("_conversionRateType")]
		public virtual byte ConversionRateType
		{
			get
			{
				return this._conversionRateType;
			}
			set
			{
				this._conversionRateType = value;
			}
		}
		
		private Client _client;
		[ForeignKeyAssociation(SharedFields = "ClientId", TargetFields = "Id")]
		[Storage("_client")]
		public virtual Client Client
		{
			get
			{
				return this._client;
			}
			set
			{
				this._client = value;
			}
		}
		
		private User _user;
		[ForeignKeyAssociation(SharedFields = "RecCreatedBy", TargetFields = "Id")]
		[Storage("_user")]
		public virtual User RecCreatedByUser
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
		private User _user1;
		[ForeignKeyAssociation(SharedFields = "RecModifiedBy", TargetFields = "Id")]
		[Storage("_user1")]
		public virtual User RecModifiedByUser
		{
			get
			{
				return this._user1;
			}
			set
			{
				this._user1 = value;
			}
		}
		
		private Organization _organization;
		[ForeignKeyAssociation(SharedFields = "OrganizationId", TargetFields = "Id")]
		[Storage("_organization")]
		public virtual Organization Organization
		{
			get
			{
				return this._organization;
			}
			set
			{
				this._organization = value;
			}
		}
		
		private Currency _currency;
		[ForeignKeyAssociation(SharedFields = "CurrencyId", TargetFields = "Id")]
		[Storage("_currency")]
		public virtual Currency Currency
		{
			get
			{
				return this._currency;
			}
			set
			{
				this._currency = value;
			}
		}
		
		private Currency _currency1;
		[ForeignKeyAssociation(SharedFields = "CurrencyIdTo", TargetFields = "Id")]
		[Storage("_currency1")]
		public virtual Currency CurrencyTo
		{
			get
			{
				return this._currency1;
			}
			set
			{
				this._currency1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
