#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using MyERP.DataAccess;

namespace MyERP.DataAccess	
{
	public partial class GeneralJournalSetup : IDataErrorInfo, INotifyPropertyChanging, INotifyPropertyChanged
	{
		private Guid _id;
		public virtual Guid Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private Guid _organizationId;
		public virtual Guid OrganizationId
		{
			get
			{
				return this._organizationId;
			}
			set
			{
				if(this._organizationId != value)
				{
					this.OnPropertyChanging("OrganizationId");
					this._organizationId = value;
					this.OnPropertyChanged("OrganizationId");
				}
			}
		}
		
		private Guid _clientId;
		public virtual Guid ClientId
		{
			get
			{
				return this._clientId;
			}
			set
			{
				if(this._clientId != value)
				{
					this.OnPropertyChanging("ClientId");
					this._clientId = value;
					this.OnPropertyChanged("ClientId");
				}
			}
		}
		
		private Guid _localCurrencyId;
		public virtual Guid LocalCurrencyId
		{
			get
			{
				return this._localCurrencyId;
			}
			set
			{
				if(this._localCurrencyId != value)
				{
					this.OnPropertyChanging("LocalCurrencyId");
					this._localCurrencyId = value;
					this.OnPropertyChanged("LocalCurrencyId");
				}
			}
		}
		
		private int _lcyExchangeRateUnit;
		public virtual int LcyExchangeRateUnit
		{
			get
			{
				return this._lcyExchangeRateUnit;
			}
			set
			{
				if(this._lcyExchangeRateUnit != value)
				{
					this.OnPropertyChanging("LcyExchangeRateUnit");
					this._lcyExchangeRateUnit = value;
					this.OnPropertyChanged("LcyExchangeRateUnit");
				}
			}
		}
		
		private Guid _generalJournalNumberSequenceId;
		public virtual Guid GeneralJournalNumberSequenceId
		{
			get
			{
				return this._generalJournalNumberSequenceId;
			}
			set
			{
				if(this._generalJournalNumberSequenceId != value)
				{
					this.OnPropertyChanging("GeneralJournalNumberSequenceId");
					this._generalJournalNumberSequenceId = value;
					this.OnPropertyChanged("GeneralJournalNumberSequenceId");
				}
			}
		}
		
		private DateTime _recCreated;
		public virtual DateTime RecCreated
		{
			get
			{
				return this._recCreated;
			}
			set
			{
				if(this._recCreated != value)
				{
					this.OnPropertyChanging("RecCreated");
					this._recCreated = value;
					this.OnPropertyChanged("RecCreated");
				}
			}
		}
		
		private DateTime _recModified;
		public virtual DateTime RecModified
		{
			get
			{
				return this._recModified;
			}
			set
			{
				if(this._recModified != value)
				{
					this.OnPropertyChanging("RecModified");
					this._recModified = value;
					this.OnPropertyChanged("RecModified");
				}
			}
		}
		
		private Guid _recCreatedBy;
		public virtual Guid RecCreatedBy
		{
			get
			{
				return this._recCreatedBy;
			}
			set
			{
				if(this._recCreatedBy != value)
				{
					this.OnPropertyChanging("RecCreatedBy");
					this._recCreatedBy = value;
					this.OnPropertyChanged("RecCreatedBy");
				}
			}
		}
		
		private Guid _recModifiedBy;
		public virtual Guid RecModifiedBy
		{
			get
			{
				return this._recModifiedBy;
			}
			set
			{
				if(this._recModifiedBy != value)
				{
					this.OnPropertyChanging("RecModifiedBy");
					this._recModifiedBy = value;
					this.OnPropertyChanged("RecModifiedBy");
				}
			}
		}
		
		private long _version;
		public virtual long Version
		{
			get
			{
				return this._version;
			}
			set
			{
				if(this._version != value)
				{
					this.OnPropertyChanging("Version");
					this._version = value;
					this.OnPropertyChanged("Version");
				}
			}
		}
		
		private User _recCreatedByUser;
		public virtual User RecCreatedByUser
		{
			get
			{
				return this._recCreatedByUser;
			}
			set
			{
				if(this._recCreatedByUser != value)
				{
					this.OnPropertyChanging("RecCreatedByUser");
					this._recCreatedByUser = value;
					this.OnPropertyChanged("RecCreatedByUser");
				}
			}
		}
		
		private User _recModifiedByUser;
		public virtual User RecModifiedByUser
		{
			get
			{
				return this._recModifiedByUser;
			}
			set
			{
				if(this._recModifiedByUser != value)
				{
					this.OnPropertyChanging("RecModifiedByUser");
					this._recModifiedByUser = value;
					this.OnPropertyChanged("RecModifiedByUser");
				}
			}
		}
		
		private Organization _organization;
		public virtual Organization Organization
		{
			get
			{
				return this._organization;
			}
			set
			{
				if(this._organization != value)
				{
					this.OnPropertyChanging("Organization");
					this._organization = value;
					this.OnPropertyChanged("Organization");
				}
			}
		}
		
		private Currency _localCurrency;
		public virtual Currency LocalCurrency
		{
			get
			{
				return this._localCurrency;
			}
			set
			{
				if(this._localCurrency != value)
				{
					this.OnPropertyChanging("LocalCurrency");
					this._localCurrency = value;
					this.OnPropertyChanged("LocalCurrency");
				}
			}
		}
		
		private NumberSequence _generalJournalNumberSequence;
		public virtual NumberSequence GeneralJournalNumberSequence
		{
			get
			{
				return this._generalJournalNumberSequence;
			}
			set
			{
				if(this._generalJournalNumberSequence != value)
				{
					this.OnPropertyChanging("GeneralJournalNumberSequence");
					this._generalJournalNumberSequence = value;
					this.OnPropertyChanged("GeneralJournalNumberSequence");
				}
			}
		}
		
		private Client _client;
		public virtual Client Client
		{
			get
			{
				return this._client;
			}
			set
			{
				if(this._client != value)
				{
					this.OnPropertyChanging("Client");
					this._client = value;
					this.OnPropertyChanged("Client");
				}
			}
		}
		
		#region IDataErrorInfo members
		
		private string error = string.Empty;
		public string Error
		{
			get
			{
				return this.error;
			}
		}
		
		public string this[string propertyName]
		{
			get
			{
				this.ValidatePropertyInternal(propertyName, ref this.error);
		
				return this.error;
			}
		}
		
		protected virtual void ValidatePropertyInternal(string propertyName, ref string error)
		{
		    this.ValidateProperty(propertyName, ref error);
		}
		
		// Please implement this method in a partial class in order to provide the error message depending on each of the properties.
		partial void ValidateProperty(string propertyName, ref string error);
		
		#endregion
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
