#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MyERP.DataAccess;

namespace MyERP.DataAccess	
{
	[Table("general_journal_document", UpdateSchema = true)]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Version)]
	public partial class GeneralJournalDocument
	{
		private Guid _Stt_Rec;
		[Column("id", IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "uuid")]
		[Storage("_Stt_Rec")]
		public virtual Guid Id
		{
			get
			{
				return this._Stt_Rec;
			}
			set
			{
				this._Stt_Rec = value;
			}
		}
		
		private Guid _clientId;
		[Column("client_id", Length = 0, Scale = 0, SqlType = "uuid")]
		[Storage("_clientId")]
		public virtual Guid ClientId
		{
			get
			{
				return this._clientId;
			}
			set
			{
				this._clientId = value;
			}
		}
		
		private Guid _organizaionId;
		[Column("organizaion_id", Length = 0, Scale = 0, SqlType = "uuid")]
		[Storage("_organizaionId")]
		public virtual Guid OrganizaionId
		{
			get
			{
				return this._organizaionId;
			}
			set
			{
				this._organizaionId = value;
			}
		}
		
		private long _version;
		[Column("version", IsVersion = true, IsBackendVersion = true, Length = 0, Scale = 0, SqlType = "int8")]
		[Storage("_version")]
		public virtual long Version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
		
		private decimal _totalCreditAmountLcy;
		[Column("total_credit_amount_lcy", Length = 38, Scale = 20, SqlType = "numeric")]
		[Storage("_totalCreditAmountLcy")]
		public virtual decimal TotalCreditAmountLcy
		{
			get
			{
				return this._totalCreditAmountLcy;
			}
			set
			{
				this._totalCreditAmountLcy = value;
			}
		}
		
		private Guid _noSeriesId;
		[Column("noseries_id", Length = 0, Scale = 0, SqlType = "uuid")]
		[Storage("_noSeriesId")]
		public virtual Guid NoSeriesId
		{
			get
			{
				return this._noSeriesId;
			}
			set
			{
				this._noSeriesId = value;
			}
		}
		
		private DateTime _documentCreated;
		[Column("document_created_date", Length = 0, Scale = 0, SqlType = "date")]
		[Storage("_documentCreated")]
		public virtual DateTime DocumentCreated
		{
			get
			{
				return this._documentCreated;
			}
			set
			{
				this._documentCreated = value;
			}
		}
		
		private string _documentNo;
		[Column("document_no", Length = 0, Scale = 0, SqlType = "varchar")]
		[Storage("_documentNo")]
		public virtual string DocumentNo
		{
			get
			{
				return this._documentNo;
			}
			set
			{
				this._documentNo = value;
			}
		}
		
		private DateTime _documentPosted;
		[Column("document_posted_date", Length = 0, Scale = 0, SqlType = "date")]
		[Storage("_documentPosted")]
		public virtual DateTime DocumentPosted
		{
			get
			{
				return this._documentPosted;
			}
			set
			{
				this._documentPosted = value;
			}
		}
		
		private string _documentType;
		[Column("document_type", Length = 0, Scale = 0, SqlType = "varchar")]
		[Storage("_documentType")]
		public virtual string DocumentType
		{
			get
			{
				return this._documentType;
			}
			set
			{
				this._documentType = value;
			}
		}
		
		private DateTime _recCreated;
		[Column("rec_created", Length = 0, Scale = 0, SqlType = "timestamp")]
		[Storage("_recCreated")]
		public virtual DateTime RecCreated
		{
			get
			{
				return this._recCreated;
			}
			set
			{
				this._recCreated = value;
			}
		}
		
		private Guid _recCreatedBy;
		[Column("rec_created_by", Length = 0, Scale = 0, SqlType = "uuid")]
		[Storage("_recCreatedBy")]
		public virtual Guid RecCreatedBy
		{
			get
			{
				return this._recCreatedBy;
			}
			set
			{
				this._recCreatedBy = value;
			}
		}
		
		private DateTime _recModified;
		[Column("rec_modified", Length = 0, Scale = 0, SqlType = "timestamp")]
		[Storage("_recModified")]
		public virtual DateTime RecModified
		{
			get
			{
				return this._recModified;
			}
			set
			{
				this._recModified = value;
			}
		}
		
		private Guid _recModifiedBy;
		[Column("rec_modified_by", Length = 0, Scale = 0, SqlType = "uuid")]
		[Storage("_recModifiedBy")]
		public virtual Guid RecModifiedBy
		{
			get
			{
				return this._recModifiedBy;
			}
			set
			{
				this._recModifiedBy = value;
			}
		}
		
		private int _status;
		[Column("status", Length = 0, Scale = 0, SqlType = "int4")]
		[Storage("_status")]
		public virtual int Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private decimal _totalCreditAmount;
		[Column("total_credit_amount", Length = 38, Scale = 20, SqlType = "numeric")]
		[Storage("_totalCreditAmount")]
		public virtual decimal TotalCreditAmount
		{
			get
			{
				return this._totalCreditAmount;
			}
			set
			{
				this._totalCreditAmount = value;
			}
		}
		
		private decimal _totalDebitAmount;
		[Column("total_debit_amount", Length = 38, Scale = 20, SqlType = "numeric")]
		[Storage("_totalDebitAmount")]
		public virtual decimal TotalDebitAmount
		{
			get
			{
				return this._totalDebitAmount;
			}
			set
			{
				this._totalDebitAmount = value;
			}
		}
		
		private decimal _totalDebitAmountLcy;
		[Column("total_debit_amount_lcy", Length = 38, Scale = 20, SqlType = "numeric")]
		[Storage("_totalDebitAmountLcy")]
		public virtual decimal TotalDebitAmountLcy
		{
			get
			{
				return this._totalDebitAmountLcy;
			}
			set
			{
				this._totalDebitAmountLcy = value;
			}
		}
		
		private int _transactionType;
		[Column("transaction_type", Length = 0, Scale = 0, SqlType = "int4")]
		[Storage("_transactionType")]
		public virtual int TransactionType
		{
			get
			{
				return this._transactionType;
			}
			set
			{
				this._transactionType = value;
			}
		}
		
		private int _currencyExchangeRate;
		[Column("currency_exchange_rate", Length = 38, Scale = 20, SqlType = "numeric")]
		[Storage("_currencyExchangeRate")]
		public virtual int CurrencyExchangeRate
		{
			get
			{
				return this._currencyExchangeRate;
			}
			set
			{
				this._currencyExchangeRate = value;
			}
		}
		
		private Guid _currencyId;
		[Column("currency_id", Length = 0, Scale = 0, SqlType = "uuid")]
		[Storage("_currencyId")]
		public virtual Guid CurrencyId
		{
			get
			{
				return this._currencyId;
			}
			set
			{
				this._currencyId = value;
			}
		}
		
		private string _description;
		[Column("description", Length = 0, Scale = 0, SqlType = "varchar")]
		[Storage("_description")]
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private Client _client;
		[ForeignKeyAssociation(SharedFields = "ClientId", TargetFields = "Id")]
		[Storage("_client")]
		public virtual Client Client
		{
			get
			{
				return this._client;
			}
			set
			{
				this._client = value;
			}
		}
		
		private Organization _organization;
		[ForeignKeyAssociation(SharedFields = "OrganizaionId", TargetFields = "Id")]
		[Storage("_organization")]
		public virtual Organization Organization
		{
			get
			{
				return this._organization;
			}
			set
			{
				this._organization = value;
			}
		}
		
		private User _userinfo;
		[ForeignKeyAssociation(SharedFields = "RecCreatedBy", TargetFields = "Id")]
		[Storage("_userinfo")]
		public virtual User RecCreatedByUser
		{
			get
			{
				return this._userinfo;
			}
			set
			{
				this._userinfo = value;
			}
		}
		
		private User _userinfo1;
		[ForeignKeyAssociation(SharedFields = "RecModifiedBy")]
		[Storage("_userinfo1")]
		public virtual User RecModifiedByUser
		{
			get
			{
				return this._userinfo1;
			}
			set
			{
				this._userinfo1 = value;
			}
		}
		
		private Currency _dmnt;
		[ForeignKeyAssociation(SharedFields = "CurrencyId", TargetFields = "Id")]
		[Storage("_dmnt")]
		public virtual Currency Currency
		{
			get
			{
				return this._dmnt;
			}
			set
			{
				this._dmnt = value;
			}
		}
		
		private NoSeries _noSeries;
		[ForeignKeyAssociation(SharedFields = "NoSeriesId", TargetFields = "Id")]
		[Storage("_noSeries")]
		public virtual NoSeries NoSeries
		{
			get
			{
				return this._noSeries;
			}
			set
			{
				this._noSeries = value;
			}
		}
		
		private IList<GeneralJournalLine> _ct11 = new List<GeneralJournalLine>();
		[Collection(InverseProperty = "TransactionDocument")]
		[Storage("_ct11")]
		public virtual IList<GeneralJournalLine> TransactionLines
		{
			get
			{
				return this._ct11;
			}
		}
		
	}
}
#pragma warning restore 1591
