#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using MyERP.DataAccess;

namespace MyERP.DataAccess	
{
	public partial class User : IDataErrorInfo, INotifyPropertyChanging, INotifyPropertyChanged
	{
		private Guid _id;
		public virtual Guid Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				if(this._name != value)
				{
					this.OnPropertyChanging("Name");
					this._name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				if(this._password != value)
				{
					this.OnPropertyChanging("Password");
					this._password = value;
					this.OnPropertyChanged("Password");
				}
			}
		}
		
		private string _comment;
		public virtual string Comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if(this._comment != value)
				{
					this.OnPropertyChanging("Comment");
					this._comment = value;
					this.OnPropertyChanged("Comment");
				}
			}
		}
		
		private string _fullName;
		public virtual string FullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if(this._fullName != value)
				{
					this.OnPropertyChanging("FullName");
					this._fullName = value;
					this.OnPropertyChanged("FullName");
				}
			}
		}
		
		private string _passwordAnswer;
		public virtual string PasswordAnswer
		{
			get
			{
				return this._passwordAnswer;
			}
			set
			{
				if(this._passwordAnswer != value)
				{
					this.OnPropertyChanging("PasswordAnswer");
					this._passwordAnswer = value;
					this.OnPropertyChanged("PasswordAnswer");
				}
			}
		}
		
		private string _passwordQuestion;
		public virtual string PasswordQuestion
		{
			get
			{
				return this._passwordQuestion;
			}
			set
			{
				if(this._passwordQuestion != value)
				{
					this.OnPropertyChanging("PasswordQuestion");
					this._passwordQuestion = value;
					this.OnPropertyChanged("PasswordQuestion");
				}
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				if(this._email != value)
				{
					this.OnPropertyChanging("Email");
					this._email = value;
					this.OnPropertyChanged("Email");
				}
			}
		}
		
		private DateTime _createdDate;
		public virtual DateTime CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				if(this._createdDate != value)
				{
					this.OnPropertyChanging("CreatedDate");
					this._createdDate = value;
					this.OnPropertyChanged("CreatedDate");
				}
			}
		}
		
		private bool _isActivated;
		public virtual bool IsActivated
		{
			get
			{
				return this._isActivated;
			}
			set
			{
				if(this._isActivated != value)
				{
					this.OnPropertyChanging("IsActivated");
					this._isActivated = value;
					this.OnPropertyChanged("IsActivated");
				}
			}
		}
		
		private bool _isLockedOut;
		public virtual bool IsLockedOut
		{
			get
			{
				return this._isLockedOut;
			}
			set
			{
				if(this._isLockedOut != value)
				{
					this.OnPropertyChanging("IsLockedOut");
					this._isLockedOut = value;
					this.OnPropertyChanged("IsLockedOut");
				}
			}
		}
		
		private DateTime _lastLockedOutDate;
		public virtual DateTime LastLockedOutDate
		{
			get
			{
				return this._lastLockedOutDate;
			}
			set
			{
				if(this._lastLockedOutDate != value)
				{
					this.OnPropertyChanging("LastLockedOutDate");
					this._lastLockedOutDate = value;
					this.OnPropertyChanged("LastLockedOutDate");
				}
			}
		}
		
		private string _lastLockedOutReason;
		public virtual string LastLockedOutReason
		{
			get
			{
				return this._lastLockedOutReason;
			}
			set
			{
				if(this._lastLockedOutReason != value)
				{
					this.OnPropertyChanging("LastLockedOutReason");
					this._lastLockedOutReason = value;
					this.OnPropertyChanged("LastLockedOutReason");
				}
			}
		}
		
		private DateTime _lastLoginDate;
		public virtual DateTime LastLoginDate
		{
			get
			{
				return this._lastLoginDate;
			}
			set
			{
				if(this._lastLoginDate != value)
				{
					this.OnPropertyChanging("LastLoginDate");
					this._lastLoginDate = value;
					this.OnPropertyChanged("LastLoginDate");
				}
			}
		}
		
		private string _lastLoginIp;
		public virtual string LastLoginIp
		{
			get
			{
				return this._lastLoginIp;
			}
			set
			{
				if(this._lastLoginIp != value)
				{
					this.OnPropertyChanging("LastLoginIp");
					this._lastLoginIp = value;
					this.OnPropertyChanged("LastLoginIp");
				}
			}
		}
		
		private DateTime _lastModifiedDate;
		public virtual DateTime LastModifiedDate
		{
			get
			{
				return this._lastModifiedDate;
			}
			set
			{
				if(this._lastModifiedDate != value)
				{
					this.OnPropertyChanging("LastModifiedDate");
					this._lastModifiedDate = value;
					this.OnPropertyChanged("LastModifiedDate");
				}
			}
		}
		
		private Guid? _clientId;
		public virtual Guid? ClientId
		{
			get
			{
				return this._clientId;
			}
			set
			{
				if(this._clientId != value)
				{
					this.OnPropertyChanging("ClientId");
					this._clientId = value;
					this.OnPropertyChanged("ClientId");
				}
			}
		}
		
		private Guid? _organizationId;
		public virtual Guid? OrganizationId
		{
			get
			{
				return this._organizationId;
			}
			set
			{
				if(this._organizationId != value)
				{
					this.OnPropertyChanging("OrganizationId");
					this._organizationId = value;
					this.OnPropertyChanged("OrganizationId");
				}
			}
		}
		
		private Client _client;
		public virtual Client Client
		{
			get
			{
				return this._client;
			}
			set
			{
				if(this._client != value)
				{
					this.OnPropertyChanging("Client");
					this._client = value;
					this.OnPropertyChanged("Client");
				}
			}
		}
		
		private Organization _organization;
		public virtual Organization Organization
		{
			get
			{
				return this._organization;
			}
			set
			{
				if(this._organization != value)
				{
					this.OnPropertyChanging("Organization");
					this._organization = value;
					this.OnPropertyChanged("Organization");
				}
			}
		}
		
		#region IDataErrorInfo members
		
		private string error = string.Empty;
		public string Error
		{
			get
			{
				return this.error;
			}
		}
		
		public string this[string propertyName]
		{
			get
			{
				this.ValidatePropertyInternal(propertyName, ref this.error);
		
				return this.error;
			}
		}
		
		protected virtual void ValidatePropertyInternal(string propertyName, ref string error)
		{
		    this.ValidateProperty(propertyName, ref error);
		}
		
		// Please implement this method in a partial class in order to provide the error message depending on each of the properties.
		partial void ValidateProperty(string propertyName, ref string error);
		
		#endregion
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
