//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 04/21/2021 10:23:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyERP.DataAccess
{
    public partial class GeneralJournalHeader : INotifyPropertyChanging, INotifyPropertyChanged
    {

        public GeneralJournalHeader()
        {
            OnCreated();
        }

        #region Properties

        [Key]
        [Required()]
        public virtual long Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    this.OnIdChanging(value);
                    OnPropertyChanging("Id");
                    _Id = value;
                    this.OnIdChanged();
                    OnPropertyChanged("Id");
                }
            }
        }
        private long _Id;

        [Required()]
        public virtual byte DocumentType
        {
            get
            {
                return _DocumentType;
            }
            set
            {
                if (_DocumentType != value)
                {
                    this.OnDocumentTypeChanging(value);
                    OnPropertyChanging("DocumentType");
                    _DocumentType = value;
                    this.OnDocumentTypeChanged();
                    OnPropertyChanged("DocumentType");
                }
            }
        }
        private byte _DocumentType;

        [Required()]
        public virtual byte DocSubType
        {
            get
            {
                return _DocSubType;
            }
            set
            {
                if (_DocSubType != value)
                {
                    this.OnDocSubTypeChanging(value);
                    OnPropertyChanging("DocSubType");
                    _DocSubType = value;
                    this.OnDocSubTypeChanged();
                    OnPropertyChanged("DocSubType");
                }
            }
        }
        private byte _DocSubType;

        [Required()]
        public virtual long DocSequenceId
        {
            get
            {
                return _DocSequenceId;
            }
            set
            {
                if (_DocSequenceId != value)
                {
                    this.OnDocSequenceIdChanging(value);
                    OnPropertyChanging("DocSequenceId");
                    _DocSequenceId = value;
                    this.OnDocSequenceIdChanged();
                    OnPropertyChanged("DocSequenceId");
                }
            }
        }
        private long _DocSequenceId;

        [StringLength(32)]
        [Required()]
        public virtual string DocumentNo
        {
            get
            {
                return _DocumentNo;
            }
            set
            {
                if (_DocumentNo != value)
                {
                    this.OnDocumentNoChanging(value);
                    OnPropertyChanging("DocumentNo");
                    _DocumentNo = value;
                    this.OnDocumentNoChanged();
                    OnPropertyChanged("DocumentNo");
                }
            }
        }
        private string _DocumentNo;

        [Required()]
        public virtual global::System.DateTime DocumentDate
        {
            get
            {
                return _DocumentDate;
            }
            set
            {
                if (_DocumentDate != value)
                {
                    this.OnDocumentDateChanging(value);
                    OnPropertyChanging("DocumentDate");
                    _DocumentDate = value;
                    this.OnDocumentDateChanged();
                    OnPropertyChanged("DocumentDate");
                }
            }
        }
        private global::System.DateTime _DocumentDate;

        public virtual global::System.DateTime? PostingDate
        {
            get
            {
                return _PostingDate;
            }
            set
            {
                if (_PostingDate != value)
                {
                    this.OnPostingDateChanging(value);
                    OnPropertyChanging("PostingDate");
                    _PostingDate = value;
                    this.OnPostingDateChanged();
                    OnPropertyChanged("PostingDate");
                }
            }
        }
        private global::System.DateTime? _PostingDate;

        [Required()]
        public virtual long CurrencyId
        {
            get
            {
                return _CurrencyId;
            }
            set
            {
                if (_CurrencyId != value)
                {
                    this.OnCurrencyIdChanging(value);
                    OnPropertyChanging("CurrencyId");
                    _CurrencyId = value;
                    this.OnCurrencyIdChanged();
                    OnPropertyChanged("CurrencyId");
                }
            }
        }
        private long _CurrencyId;

        [Required()]
        public virtual decimal CurrencyFactor
        {
            get
            {
                return _CurrencyFactor;
            }
            set
            {
                if (_CurrencyFactor != value)
                {
                    this.OnCurrencyFactorChanging(value);
                    OnPropertyChanging("CurrencyFactor");
                    _CurrencyFactor = value;
                    this.OnCurrencyFactorChanged();
                    OnPropertyChanged("CurrencyFactor");
                }
            }
        }
        private decimal _CurrencyFactor;

        public virtual int? NoPrinted
        {
            get
            {
                return _NoPrinted;
            }
            set
            {
                if (_NoPrinted != value)
                {
                    this.OnNoPrintedChanging(value);
                    OnPropertyChanging("NoPrinted");
                    _NoPrinted = value;
                    this.OnNoPrintedChanged();
                    OnPropertyChanged("NoPrinted");
                }
            }
        }
        private int? _NoPrinted;

        [Required()]
        public virtual long OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                if (_OrganizationId != value)
                {
                    this.OnOrganizationIdChanging(value);
                    OnPropertyChanging("OrganizationId");
                    _OrganizationId = value;
                    this.OnOrganizationIdChanged();
                    OnPropertyChanged("OrganizationId");
                }
            }
        }
        private long _OrganizationId;

        [Required()]
        public virtual long ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                if (_ClientId != value)
                {
                    this.OnClientIdChanging(value);
                    OnPropertyChanging("ClientId");
                    _ClientId = value;
                    this.OnClientIdChanged();
                    OnPropertyChanged("ClientId");
                }
            }
        }
        private long _ClientId;

        [Required()]
        public virtual decimal TotalDebitAmountLCY
        {
            get
            {
                return _TotalDebitAmountLCY;
            }
            set
            {
                if (_TotalDebitAmountLCY != value)
                {
                    this.OnTotalDebitAmountLCYChanging(value);
                    OnPropertyChanging("TotalDebitAmountLCY");
                    _TotalDebitAmountLCY = value;
                    this.OnTotalDebitAmountLCYChanged();
                    OnPropertyChanged("TotalDebitAmountLCY");
                }
            }
        }
        private decimal _TotalDebitAmountLCY;

        public virtual decimal? TotalDebitAmount
        {
            get
            {
                return _TotalDebitAmount;
            }
            set
            {
                if (_TotalDebitAmount != value)
                {
                    this.OnTotalDebitAmountChanging(value);
                    OnPropertyChanging("TotalDebitAmount");
                    _TotalDebitAmount = value;
                    this.OnTotalDebitAmountChanged();
                    OnPropertyChanged("TotalDebitAmount");
                }
            }
        }
        private decimal? _TotalDebitAmount;

        [Required()]
        public virtual decimal TotalCreditAmountLCY
        {
            get
            {
                return _TotalCreditAmountLCY;
            }
            set
            {
                if (_TotalCreditAmountLCY != value)
                {
                    this.OnTotalCreditAmountLCYChanging(value);
                    OnPropertyChanging("TotalCreditAmountLCY");
                    _TotalCreditAmountLCY = value;
                    this.OnTotalCreditAmountLCYChanged();
                    OnPropertyChanged("TotalCreditAmountLCY");
                }
            }
        }
        private decimal _TotalCreditAmountLCY;

        [Required()]
        public virtual decimal TotalCreditAmount
        {
            get
            {
                return _TotalCreditAmount;
            }
            set
            {
                if (_TotalCreditAmount != value)
                {
                    this.OnTotalCreditAmountChanging(value);
                    OnPropertyChanging("TotalCreditAmount");
                    _TotalCreditAmount = value;
                    this.OnTotalCreditAmountChanged();
                    OnPropertyChanged("TotalCreditAmount");
                }
            }
        }
        private decimal _TotalCreditAmount;

        [Required()]
        public virtual long Version
        {
            get
            {
                return _Version;
            }
            set
            {
                if (_Version != value)
                {
                    this.OnVersionChanging(value);
                    OnPropertyChanging("Version");
                    _Version = value;
                    this.OnVersionChanged();
                    OnPropertyChanged("Version");
                }
            }
        }
        private long _Version;

        [Required()]
        public virtual byte Status
        {
            get
            {
                return _Status;
            }
            set
            {
                if (_Status != value)
                {
                    this.OnStatusChanging(value);
                    OnPropertyChanging("Status");
                    _Status = value;
                    this.OnStatusChanged();
                    OnPropertyChanged("Status");
                }
            }
        }
        private byte _Status;

        [Required()]
        public virtual global::System.DateTime RecCreatedAt
        {
            get
            {
                return _RecCreatedAt;
            }
            set
            {
                if (_RecCreatedAt != value)
                {
                    this.OnRecCreatedAtChanging(value);
                    OnPropertyChanging("RecCreatedAt");
                    _RecCreatedAt = value;
                    this.OnRecCreatedAtChanged();
                    OnPropertyChanged("RecCreatedAt");
                }
            }
        }
        private global::System.DateTime _RecCreatedAt;

        [Required()]
        public virtual long RecCreatedBy
        {
            get
            {
                return _RecCreatedBy;
            }
            set
            {
                if (_RecCreatedBy != value)
                {
                    this.OnRecCreatedByChanging(value);
                    OnPropertyChanging("RecCreatedBy");
                    _RecCreatedBy = value;
                    this.OnRecCreatedByChanged();
                    OnPropertyChanged("RecCreatedBy");
                }
            }
        }
        private long _RecCreatedBy;

        [Required()]
        public virtual global::System.DateTime RecModifiedAt
        {
            get
            {
                return _RecModifiedAt;
            }
            set
            {
                if (_RecModifiedAt != value)
                {
                    this.OnRecModifiedAtChanging(value);
                    OnPropertyChanging("RecModifiedAt");
                    _RecModifiedAt = value;
                    this.OnRecModifiedAtChanged();
                    OnPropertyChanged("RecModifiedAt");
                }
            }
        }
        private global::System.DateTime _RecModifiedAt;

        [Required()]
        public virtual long RecModifiedBy
        {
            get
            {
                return _RecModifiedBy;
            }
            set
            {
                if (_RecModifiedBy != value)
                {
                    this.OnRecModifiedByChanging(value);
                    OnPropertyChanging("RecModifiedBy");
                    _RecModifiedBy = value;
                    this.OnRecModifiedByChanged();
                    OnPropertyChanged("RecModifiedBy");
                }
            }
        }
        private long _RecModifiedBy;

        #endregion

        #region Navigation Properties

        public virtual ICollection<GeneralJournalLine> GeneralJournalLines { get; set; }
        public virtual Client Client
        {
            get
            {
                return _Client;
            }
            set
            {
                if (_Client != value)
                {
                    this.OnClientChanging(value);
                    OnPropertyChanging("Client");
                    _Client = value;
                    this.OnClientChanged();
                    OnPropertyChanged("Client");
                }
            }
        }
        private Client _Client;
        public virtual Organization Organization
        {
            get
            {
                return _Organization;
            }
            set
            {
                if (_Organization != value)
                {
                    this.OnOrganizationChanging(value);
                    OnPropertyChanging("Organization");
                    _Organization = value;
                    this.OnOrganizationChanged();
                    OnPropertyChanged("Organization");
                }
            }
        }
        private Organization _Organization;
        public virtual Currency Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                if (_Currency != value)
                {
                    this.OnCurrencyChanging(value);
                    OnPropertyChanging("Currency");
                    _Currency = value;
                    this.OnCurrencyChanged();
                    OnPropertyChanged("Currency");
                }
            }
        }
        private Currency _Currency;

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        partial void OnDocumentTypeChanging(byte value);
        partial void OnDocumentTypeChanged();
        partial void OnDocSubTypeChanging(byte value);
        partial void OnDocSubTypeChanged();
        partial void OnDocSequenceIdChanging(long value);
        partial void OnDocSequenceIdChanged();
        partial void OnDocumentNoChanging(string value);
        partial void OnDocumentNoChanged();
        partial void OnDocumentDateChanging(global::System.DateTime value);
        partial void OnDocumentDateChanged();
        partial void OnPostingDateChanging(global::System.DateTime? value);
        partial void OnPostingDateChanged();
        partial void OnCurrencyIdChanging(long value);
        partial void OnCurrencyIdChanged();
        partial void OnCurrencyFactorChanging(decimal value);
        partial void OnCurrencyFactorChanged();
        partial void OnNoPrintedChanging(int? value);
        partial void OnNoPrintedChanged();
        partial void OnOrganizationIdChanging(long value);
        partial void OnOrganizationIdChanged();
        partial void OnClientIdChanging(long value);
        partial void OnClientIdChanged();
        partial void OnTotalDebitAmountLCYChanging(decimal value);
        partial void OnTotalDebitAmountLCYChanged();
        partial void OnTotalDebitAmountChanging(decimal? value);
        partial void OnTotalDebitAmountChanged();
        partial void OnTotalCreditAmountLCYChanging(decimal value);
        partial void OnTotalCreditAmountLCYChanged();
        partial void OnTotalCreditAmountChanging(decimal value);
        partial void OnTotalCreditAmountChanged();
        partial void OnVersionChanging(long value);
        partial void OnVersionChanged();
        partial void OnStatusChanging(byte value);
        partial void OnStatusChanged();
        partial void OnRecCreatedAtChanging(global::System.DateTime value);
        partial void OnRecCreatedAtChanged();
        partial void OnRecCreatedByChanging(long value);
        partial void OnRecCreatedByChanged();
        partial void OnRecModifiedAtChanging(global::System.DateTime value);
        partial void OnRecModifiedAtChanged();
        partial void OnRecModifiedByChanging(long value);
        partial void OnRecModifiedByChanged();
        partial void OnClientChanging(Client value);
        partial void OnClientChanged();
        partial void OnOrganizationChanging(Organization value);
        partial void OnOrganizationChanged();
        partial void OnCurrencyChanging(Currency value);
        partial void OnCurrencyChanged();

        #endregion

        #region INotifyPropertyChanging Members

        public event PropertyChangingEventHandler PropertyChanging;

        protected void OnPropertyChanging(string propertyName) {

          if (PropertyChanging != null)
            PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
        }

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
