//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 04/21/2021 10:23:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyERP.DataAccess
{
    public partial class EInvoiceLine : INotifyPropertyChanging, INotifyPropertyChanged
    {

        public EInvoiceLine()
        {
            OnCreated();
        }

        #region Properties

        [Key]
        [Required()]
        public virtual long Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    this.OnIdChanging(value);
                    OnPropertyChanging("Id");
                    _Id = value;
                    this.OnIdChanged();
                    OnPropertyChanged("Id");
                }
            }
        }
        private long _Id;

        [Required()]
        public virtual long EInvoiceHeaderId
        {
            get
            {
                return _EInvoiceHeaderId;
            }
            set
            {
                if (_EInvoiceHeaderId != value)
                {
                    this.OnEInvoiceHeaderIdChanging(value);
                    OnPropertyChanging("EInvoiceHeaderId");
                    _EInvoiceHeaderId = value;
                    this.OnEInvoiceHeaderIdChanged();
                    OnPropertyChanged("EInvoiceHeaderId");
                }
            }
        }
        private long _EInvoiceHeaderId;

        [Required()]
        public virtual long LineNumber
        {
            get
            {
                return _LineNumber;
            }
            set
            {
                if (_LineNumber != value)
                {
                    this.OnLineNumberChanging(value);
                    OnPropertyChanging("LineNumber");
                    _LineNumber = value;
                    this.OnLineNumberChanged();
                    OnPropertyChanged("LineNumber");
                }
            }
        }
        private long _LineNumber;

        [Required()]
        public virtual long ItemId
        {
            get
            {
                return _ItemId;
            }
            set
            {
                if (_ItemId != value)
                {
                    this.OnItemIdChanging(value);
                    OnPropertyChanging("ItemId");
                    _ItemId = value;
                    this.OnItemIdChanged();
                    OnPropertyChanged("ItemId");
                }
            }
        }
        private long _ItemId;

        [StringLength(50)]
        [Required()]
        public virtual string ItemCode
        {
            get
            {
                return _ItemCode;
            }
            set
            {
                if (_ItemCode != value)
                {
                    this.OnItemCodeChanging(value);
                    OnPropertyChanging("ItemCode");
                    _ItemCode = value;
                    this.OnItemCodeChanged();
                    OnPropertyChanged("ItemCode");
                }
            }
        }
        private string _ItemCode;

        [StringLength(255)]
        [Required()]
        public virtual string ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                if (_ItemName != value)
                {
                    this.OnItemNameChanging(value);
                    OnPropertyChanging("ItemName");
                    _ItemName = value;
                    this.OnItemNameChanged();
                    OnPropertyChanged("ItemName");
                }
            }
        }
        private string _ItemName;

        [Required()]
        public virtual long UnitId
        {
            get
            {
                return _UnitId;
            }
            set
            {
                if (_UnitId != value)
                {
                    this.OnUnitIdChanging(value);
                    OnPropertyChanging("UnitId");
                    _UnitId = value;
                    this.OnUnitIdChanged();
                    OnPropertyChanged("UnitId");
                }
            }
        }
        private long _UnitId;

        [StringLength(10)]
        [Required()]
        public virtual string UnitCode
        {
            get
            {
                return _UnitCode;
            }
            set
            {
                if (_UnitCode != value)
                {
                    this.OnUnitCodeChanging(value);
                    OnPropertyChanging("UnitCode");
                    _UnitCode = value;
                    this.OnUnitCodeChanged();
                    OnPropertyChanged("UnitCode");
                }
            }
        }
        private string _UnitCode;

        [StringLength(50)]
        [Required()]
        public virtual string UnitName
        {
            get
            {
                return _UnitName;
            }
            set
            {
                if (_UnitName != value)
                {
                    this.OnUnitNameChanging(value);
                    OnPropertyChanging("UnitName");
                    _UnitName = value;
                    this.OnUnitNameChanged();
                    OnPropertyChanged("UnitName");
                }
            }
        }
        private string _UnitName;

        [Required()]
        public virtual decimal UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                if (_UnitPrice != value)
                {
                    this.OnUnitPriceChanging(value);
                    OnPropertyChanging("UnitPrice");
                    _UnitPrice = value;
                    this.OnUnitPriceChanged();
                    OnPropertyChanged("UnitPrice");
                }
            }
        }
        private decimal _UnitPrice;

        [Required()]
        public virtual decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                if (_Quantity != value)
                {
                    this.OnQuantityChanging(value);
                    OnPropertyChanging("Quantity");
                    _Quantity = value;
                    this.OnQuantityChanged();
                    OnPropertyChanged("Quantity");
                }
            }
        }
        private decimal _Quantity;

        [Required()]
        public virtual decimal ItemTotalAmountWithoutVAT
        {
            get
            {
                return _ItemTotalAmountWithoutVAT;
            }
            set
            {
                if (_ItemTotalAmountWithoutVAT != value)
                {
                    this.OnItemTotalAmountWithoutVATChanging(value);
                    OnPropertyChanging("ItemTotalAmountWithoutVAT");
                    _ItemTotalAmountWithoutVAT = value;
                    this.OnItemTotalAmountWithoutVATChanged();
                    OnPropertyChanged("ItemTotalAmountWithoutVAT");
                }
            }
        }
        private decimal _ItemTotalAmountWithoutVAT;

        [Required()]
        public virtual decimal ItemTotalAmountWithoutVATLCY
        {
            get
            {
                return _ItemTotalAmountWithoutVATLCY;
            }
            set
            {
                if (_ItemTotalAmountWithoutVATLCY != value)
                {
                    this.OnItemTotalAmountWithoutVATLCYChanging(value);
                    OnPropertyChanging("ItemTotalAmountWithoutVATLCY");
                    _ItemTotalAmountWithoutVATLCY = value;
                    this.OnItemTotalAmountWithoutVATLCYChanged();
                    OnPropertyChanged("ItemTotalAmountWithoutVATLCY");
                }
            }
        }
        private decimal _ItemTotalAmountWithoutVATLCY;

        [Required()]
        public virtual long VatId
        {
            get
            {
                return _VatId;
            }
            set
            {
                if (_VatId != value)
                {
                    this.OnVatIdChanging(value);
                    OnPropertyChanging("VatId");
                    _VatId = value;
                    this.OnVatIdChanged();
                    OnPropertyChanged("VatId");
                }
            }
        }
        private long _VatId;

        [Required()]
        public virtual short VATPercentage
        {
            get
            {
                return _VATPercentage;
            }
            set
            {
                if (_VATPercentage != value)
                {
                    this.OnVATPercentageChanging(value);
                    OnPropertyChanging("VATPercentage");
                    _VATPercentage = value;
                    this.OnVATPercentageChanged();
                    OnPropertyChanged("VATPercentage");
                }
            }
        }
        private short _VATPercentage;

        [Required()]
        public virtual decimal VATAmount
        {
            get
            {
                return _VATAmount;
            }
            set
            {
                if (_VATAmount != value)
                {
                    this.OnVATAmountChanging(value);
                    OnPropertyChanging("VATAmount");
                    _VATAmount = value;
                    this.OnVATAmountChanged();
                    OnPropertyChanged("VATAmount");
                }
            }
        }
        private decimal _VATAmount;

        [Required()]
        public virtual decimal VATAmountLCY
        {
            get
            {
                return _VATAmountLCY;
            }
            set
            {
                if (_VATAmountLCY != value)
                {
                    this.OnVATAmountLCYChanging(value);
                    OnPropertyChanging("VATAmountLCY");
                    _VATAmountLCY = value;
                    this.OnVATAmountLCYChanged();
                    OnPropertyChanged("VATAmountLCY");
                }
            }
        }
        private decimal _VATAmountLCY;

        [Required()]
        public virtual decimal ItemTotalAmountWithVAT
        {
            get
            {
                return _ItemTotalAmountWithVAT;
            }
            set
            {
                if (_ItemTotalAmountWithVAT != value)
                {
                    this.OnItemTotalAmountWithVATChanging(value);
                    OnPropertyChanging("ItemTotalAmountWithVAT");
                    _ItemTotalAmountWithVAT = value;
                    this.OnItemTotalAmountWithVATChanged();
                    OnPropertyChanged("ItemTotalAmountWithVAT");
                }
            }
        }
        private decimal _ItemTotalAmountWithVAT;

        [Required()]
        public virtual decimal ItemTotalAmountWithVATLCY
        {
            get
            {
                return _ItemTotalAmountWithVATLCY;
            }
            set
            {
                if (_ItemTotalAmountWithVATLCY != value)
                {
                    this.OnItemTotalAmountWithVATLCYChanging(value);
                    OnPropertyChanging("ItemTotalAmountWithVATLCY");
                    _ItemTotalAmountWithVATLCY = value;
                    this.OnItemTotalAmountWithVATLCYChanged();
                    OnPropertyChanged("ItemTotalAmountWithVATLCY");
                }
            }
        }
        private decimal _ItemTotalAmountWithVATLCY;

        [Required()]
        public virtual byte Promotion
        {
            get
            {
                return _Promotion;
            }
            set
            {
                if (_Promotion != value)
                {
                    this.OnPromotionChanging(value);
                    OnPropertyChanging("Promotion");
                    _Promotion = value;
                    this.OnPromotionChanged();
                    OnPropertyChanged("Promotion");
                }
            }
        }
        private byte _Promotion;

        [Required()]
        public virtual decimal AdjustmentVATAmount
        {
            get
            {
                return _AdjustmentVATAmount;
            }
            set
            {
                if (_AdjustmentVATAmount != value)
                {
                    this.OnAdjustmentVATAmountChanging(value);
                    OnPropertyChanging("AdjustmentVATAmount");
                    _AdjustmentVATAmount = value;
                    this.OnAdjustmentVATAmountChanged();
                    OnPropertyChanged("AdjustmentVATAmount");
                }
            }
        }
        private decimal _AdjustmentVATAmount;

        public virtual bool? IsIncreaseItem
        {
            get
            {
                return _IsIncreaseItem;
            }
            set
            {
                if (_IsIncreaseItem != value)
                {
                    this.OnIsIncreaseItemChanging(value);
                    OnPropertyChanging("IsIncreaseItem");
                    _IsIncreaseItem = value;
                    this.OnIsIncreaseItemChanged();
                    OnPropertyChanged("IsIncreaseItem");
                }
            }
        }
        private bool? _IsIncreaseItem;

        [Required()]
        public virtual long ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                if (_ClientId != value)
                {
                    this.OnClientIdChanging(value);
                    OnPropertyChanging("ClientId");
                    _ClientId = value;
                    this.OnClientIdChanged();
                    OnPropertyChanged("ClientId");
                }
            }
        }
        private long _ClientId;

        [Required()]
        public virtual long OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                if (_OrganizationId != value)
                {
                    this.OnOrganizationIdChanging(value);
                    OnPropertyChanging("OrganizationId");
                    _OrganizationId = value;
                    this.OnOrganizationIdChanged();
                    OnPropertyChanged("OrganizationId");
                }
            }
        }
        private long _OrganizationId;

        #endregion

        #region Navigation Properties

        public virtual EInvoiceHeader EInvoiceHeader
        {
            get
            {
                return _EInvoiceHeader;
            }
            set
            {
                if (_EInvoiceHeader != value)
                {
                    this.OnEInvoiceHeaderChanging(value);
                    OnPropertyChanging("EInvoiceHeader");
                    _EInvoiceHeader = value;
                    this.OnEInvoiceHeaderChanged();
                    OnPropertyChanged("EInvoiceHeader");
                }
            }
        }
        private EInvoiceHeader _EInvoiceHeader;
        public virtual Client Client
        {
            get
            {
                return _Client;
            }
            set
            {
                if (_Client != value)
                {
                    this.OnClientChanging(value);
                    OnPropertyChanging("Client");
                    _Client = value;
                    this.OnClientChanged();
                    OnPropertyChanged("Client");
                }
            }
        }
        private Client _Client;
        public virtual Organization Organization
        {
            get
            {
                return _Organization;
            }
            set
            {
                if (_Organization != value)
                {
                    this.OnOrganizationChanging(value);
                    OnPropertyChanging("Organization");
                    _Organization = value;
                    this.OnOrganizationChanged();
                    OnPropertyChanged("Organization");
                }
            }
        }
        private Organization _Organization;
        public virtual Vat Vat
        {
            get
            {
                return _Vat;
            }
            set
            {
                if (_Vat != value)
                {
                    this.OnVatChanging(value);
                    OnPropertyChanging("Vat");
                    _Vat = value;
                    this.OnVatChanged();
                    OnPropertyChanged("Vat");
                }
            }
        }
        private Vat _Vat;
        public virtual Item Item
        {
            get
            {
                return _Item;
            }
            set
            {
                if (_Item != value)
                {
                    this.OnItemChanging(value);
                    OnPropertyChanging("Item");
                    _Item = value;
                    this.OnItemChanged();
                    OnPropertyChanged("Item");
                }
            }
        }
        private Item _Item;
        public virtual Uom Uom
        {
            get
            {
                return _Uom;
            }
            set
            {
                if (_Uom != value)
                {
                    this.OnUomChanging(value);
                    OnPropertyChanging("Uom");
                    _Uom = value;
                    this.OnUomChanged();
                    OnPropertyChanged("Uom");
                }
            }
        }
        private Uom _Uom;

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        partial void OnEInvoiceHeaderIdChanging(long value);
        partial void OnEInvoiceHeaderIdChanged();
        partial void OnLineNumberChanging(long value);
        partial void OnLineNumberChanged();
        partial void OnItemIdChanging(long value);
        partial void OnItemIdChanged();
        partial void OnItemCodeChanging(string value);
        partial void OnItemCodeChanged();
        partial void OnItemNameChanging(string value);
        partial void OnItemNameChanged();
        partial void OnUnitIdChanging(long value);
        partial void OnUnitIdChanged();
        partial void OnUnitCodeChanging(string value);
        partial void OnUnitCodeChanged();
        partial void OnUnitNameChanging(string value);
        partial void OnUnitNameChanged();
        partial void OnUnitPriceChanging(decimal value);
        partial void OnUnitPriceChanged();
        partial void OnQuantityChanging(decimal value);
        partial void OnQuantityChanged();
        partial void OnItemTotalAmountWithoutVATChanging(decimal value);
        partial void OnItemTotalAmountWithoutVATChanged();
        partial void OnItemTotalAmountWithoutVATLCYChanging(decimal value);
        partial void OnItemTotalAmountWithoutVATLCYChanged();
        partial void OnVatIdChanging(long value);
        partial void OnVatIdChanged();
        partial void OnVATPercentageChanging(short value);
        partial void OnVATPercentageChanged();
        partial void OnVATAmountChanging(decimal value);
        partial void OnVATAmountChanged();
        partial void OnVATAmountLCYChanging(decimal value);
        partial void OnVATAmountLCYChanged();
        partial void OnItemTotalAmountWithVATChanging(decimal value);
        partial void OnItemTotalAmountWithVATChanged();
        partial void OnItemTotalAmountWithVATLCYChanging(decimal value);
        partial void OnItemTotalAmountWithVATLCYChanged();
        partial void OnPromotionChanging(byte value);
        partial void OnPromotionChanged();
        partial void OnAdjustmentVATAmountChanging(decimal value);
        partial void OnAdjustmentVATAmountChanged();
        partial void OnIsIncreaseItemChanging(bool? value);
        partial void OnIsIncreaseItemChanged();
        partial void OnClientIdChanging(long value);
        partial void OnClientIdChanged();
        partial void OnOrganizationIdChanging(long value);
        partial void OnOrganizationIdChanged();
        partial void OnEInvoiceHeaderChanging(EInvoiceHeader value);
        partial void OnEInvoiceHeaderChanged();
        partial void OnClientChanging(Client value);
        partial void OnClientChanged();
        partial void OnOrganizationChanging(Organization value);
        partial void OnOrganizationChanged();
        partial void OnVatChanging(Vat value);
        partial void OnVatChanged();
        partial void OnItemChanging(Item value);
        partial void OnItemChanged();
        partial void OnUomChanging(Uom value);
        partial void OnUomChanged();

        #endregion

        #region INotifyPropertyChanging Members

        public event PropertyChangingEventHandler PropertyChanging;

        protected void OnPropertyChanging(string propertyName) {

          if (PropertyChanging != null)
            PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
        }

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
