//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 04/21/2021 10:23:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyERP.DataAccess
{
    public partial class PosLine : INotifyPropertyChanging, INotifyPropertyChanged
    {

        public PosLine()
        {
            OnCreated();
        }

        #region Properties

        [Key]
        [Required()]
        public virtual long Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    this.OnIdChanging(value);
                    OnPropertyChanging("Id");
                    _Id = value;
                    this.OnIdChanged();
                    OnPropertyChanged("Id");
                }
            }
        }
        private long _Id;

        public virtual long? PosHeaderId
        {
            get
            {
                return _PosHeaderId;
            }
            set
            {
                if (_PosHeaderId != value)
                {
                    this.OnPosHeaderIdChanging(value);
                    OnPropertyChanging("PosHeaderId");
                    _PosHeaderId = value;
                    this.OnPosHeaderIdChanged();
                    OnPropertyChanged("PosHeaderId");
                }
            }
        }
        private long? _PosHeaderId;

        [Required()]
        public virtual long LineNo
        {
            get
            {
                return _LineNo;
            }
            set
            {
                if (_LineNo != value)
                {
                    this.OnLineNoChanging(value);
                    OnPropertyChanging("LineNo");
                    _LineNo = value;
                    this.OnLineNoChanged();
                    OnPropertyChanged("LineNo");
                }
            }
        }
        private long _LineNo;

        [Required()]
        public virtual byte Type
        {
            get
            {
                return _Type;
            }
            set
            {
                if (_Type != value)
                {
                    this.OnTypeChanging(value);
                    OnPropertyChanging("Type");
                    _Type = value;
                    this.OnTypeChanged();
                    OnPropertyChanged("Type");
                }
            }
        }
        private byte _Type;

        public virtual long? ItemId
        {
            get
            {
                return _ItemId;
            }
            set
            {
                if (_ItemId != value)
                {
                    this.OnItemIdChanging(value);
                    OnPropertyChanging("ItemId");
                    _ItemId = value;
                    this.OnItemIdChanged();
                    OnPropertyChanged("ItemId");
                }
            }
        }
        private long? _ItemId;

        public virtual long? LocationId
        {
            get
            {
                return _LocationId;
            }
            set
            {
                if (_LocationId != value)
                {
                    this.OnLocationIdChanging(value);
                    OnPropertyChanging("LocationId");
                    _LocationId = value;
                    this.OnLocationIdChanged();
                    OnPropertyChanged("LocationId");
                }
            }
        }
        private long? _LocationId;

        [StringLength(256)]
        public virtual string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                if (_Description != value)
                {
                    this.OnDescriptionChanging(value);
                    OnPropertyChanging("Description");
                    _Description = value;
                    this.OnDescriptionChanged();
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _Description;

        public virtual long? UomId
        {
            get
            {
                return _UomId;
            }
            set
            {
                if (_UomId != value)
                {
                    this.OnUomIdChanging(value);
                    OnPropertyChanging("UomId");
                    _UomId = value;
                    this.OnUomIdChanged();
                    OnPropertyChanged("UomId");
                }
            }
        }
        private long? _UomId;

        [StringLength(256)]
        public virtual string UomDescription
        {
            get
            {
                return _UomDescription;
            }
            set
            {
                if (_UomDescription != value)
                {
                    this.OnUomDescriptionChanging(value);
                    OnPropertyChanging("UomDescription");
                    _UomDescription = value;
                    this.OnUomDescriptionChanged();
                    OnPropertyChanged("UomDescription");
                }
            }
        }
        private string _UomDescription;

        [Required()]
        public virtual decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                if (_Quantity != value)
                {
                    this.OnQuantityChanging(value);
                    OnPropertyChanging("Quantity");
                    _Quantity = value;
                    this.OnQuantityChanged();
                    OnPropertyChanged("Quantity");
                }
            }
        }
        private decimal _Quantity;

        public virtual long? SalesPriceId
        {
            get
            {
                return _SalesPriceId;
            }
            set
            {
                if (_SalesPriceId != value)
                {
                    this.OnSalesPriceIdChanging(value);
                    OnPropertyChanging("SalesPriceId");
                    _SalesPriceId = value;
                    this.OnSalesPriceIdChanged();
                    OnPropertyChanged("SalesPriceId");
                }
            }
        }
        private long? _SalesPriceId;

        [Required()]
        public virtual decimal UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                if (_UnitPrice != value)
                {
                    this.OnUnitPriceChanging(value);
                    OnPropertyChanging("UnitPrice");
                    _UnitPrice = value;
                    this.OnUnitPriceChanged();
                    OnPropertyChanged("UnitPrice");
                }
            }
        }
        private decimal _UnitPrice;

        [Required()]
        public virtual decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                if (_Amount != value)
                {
                    this.OnAmountChanging(value);
                    OnPropertyChanging("Amount");
                    _Amount = value;
                    this.OnAmountChanged();
                    OnPropertyChanged("Amount");
                }
            }
        }
        private decimal _Amount;

        public virtual long? VatIdentifierId
        {
            get
            {
                return _VatIdentifierId;
            }
            set
            {
                if (_VatIdentifierId != value)
                {
                    this.OnVatIdentifierIdChanging(value);
                    OnPropertyChanging("VatIdentifierId");
                    _VatIdentifierId = value;
                    this.OnVatIdentifierIdChanged();
                    OnPropertyChanged("VatIdentifierId");
                }
            }
        }
        private long? _VatIdentifierId;

        [Required()]
        public virtual short VatPercentage
        {
            get
            {
                return _VatPercentage;
            }
            set
            {
                if (_VatPercentage != value)
                {
                    this.OnVatPercentageChanging(value);
                    OnPropertyChanging("VatPercentage");
                    _VatPercentage = value;
                    this.OnVatPercentageChanged();
                    OnPropertyChanged("VatPercentage");
                }
            }
        }
        private short _VatPercentage;

        [Required()]
        public virtual decimal VatAmount
        {
            get
            {
                return _VatAmount;
            }
            set
            {
                if (_VatAmount != value)
                {
                    this.OnVatAmountChanging(value);
                    OnPropertyChanging("VatAmount");
                    _VatAmount = value;
                    this.OnVatAmountChanged();
                    OnPropertyChanged("VatAmount");
                }
            }
        }
        private decimal _VatAmount;

        public virtual long? DiscountId
        {
            get
            {
                return _DiscountId;
            }
            set
            {
                if (_DiscountId != value)
                {
                    this.OnDiscountIdChanging(value);
                    OnPropertyChanging("DiscountId");
                    _DiscountId = value;
                    this.OnDiscountIdChanged();
                    OnPropertyChanged("DiscountId");
                }
            }
        }
        private long? _DiscountId;

        [Required()]
        public virtual byte LineDiscountPercentage
        {
            get
            {
                return _LineDiscountPercentage;
            }
            set
            {
                if (_LineDiscountPercentage != value)
                {
                    this.OnLineDiscountPercentageChanging(value);
                    OnPropertyChanging("LineDiscountPercentage");
                    _LineDiscountPercentage = value;
                    this.OnLineDiscountPercentageChanged();
                    OnPropertyChanged("LineDiscountPercentage");
                }
            }
        }
        private byte _LineDiscountPercentage;

        [Required()]
        public virtual decimal LineDiscountAmount
        {
            get
            {
                return _LineDiscountAmount;
            }
            set
            {
                if (_LineDiscountAmount != value)
                {
                    this.OnLineDiscountAmountChanging(value);
                    OnPropertyChanging("LineDiscountAmount");
                    _LineDiscountAmount = value;
                    this.OnLineDiscountAmountChanged();
                    OnPropertyChanged("LineDiscountAmount");
                }
            }
        }
        private decimal _LineDiscountAmount;

        [Required()]
        public virtual decimal InvoiceDiscountAmount
        {
            get
            {
                return _InvoiceDiscountAmount;
            }
            set
            {
                if (_InvoiceDiscountAmount != value)
                {
                    this.OnInvoiceDiscountAmountChanging(value);
                    OnPropertyChanging("InvoiceDiscountAmount");
                    _InvoiceDiscountAmount = value;
                    this.OnInvoiceDiscountAmountChanged();
                    OnPropertyChanged("InvoiceDiscountAmount");
                }
            }
        }
        private decimal _InvoiceDiscountAmount;

        [Required()]
        public virtual decimal UnitPriceLCY
        {
            get
            {
                return _UnitPriceLCY;
            }
            set
            {
                if (_UnitPriceLCY != value)
                {
                    this.OnUnitPriceLCYChanging(value);
                    OnPropertyChanging("UnitPriceLCY");
                    _UnitPriceLCY = value;
                    this.OnUnitPriceLCYChanged();
                    OnPropertyChanged("UnitPriceLCY");
                }
            }
        }
        private decimal _UnitPriceLCY;

        [Required()]
        public virtual decimal AmountLCY
        {
            get
            {
                return _AmountLCY;
            }
            set
            {
                if (_AmountLCY != value)
                {
                    this.OnAmountLCYChanging(value);
                    OnPropertyChanging("AmountLCY");
                    _AmountLCY = value;
                    this.OnAmountLCYChanged();
                    OnPropertyChanged("AmountLCY");
                }
            }
        }
        private decimal _AmountLCY;

        [Required()]
        public virtual decimal VatAmountLCY
        {
            get
            {
                return _VatAmountLCY;
            }
            set
            {
                if (_VatAmountLCY != value)
                {
                    this.OnVatAmountLCYChanging(value);
                    OnPropertyChanging("VatAmountLCY");
                    _VatAmountLCY = value;
                    this.OnVatAmountLCYChanged();
                    OnPropertyChanged("VatAmountLCY");
                }
            }
        }
        private decimal _VatAmountLCY;

        [Required()]
        public virtual decimal LineDiscountAmountLCY
        {
            get
            {
                return _LineDiscountAmountLCY;
            }
            set
            {
                if (_LineDiscountAmountLCY != value)
                {
                    this.OnLineDiscountAmountLCYChanging(value);
                    OnPropertyChanging("LineDiscountAmountLCY");
                    _LineDiscountAmountLCY = value;
                    this.OnLineDiscountAmountLCYChanged();
                    OnPropertyChanged("LineDiscountAmountLCY");
                }
            }
        }
        private decimal _LineDiscountAmountLCY;

        [Required()]
        public virtual decimal InvoiceDiscountAmountLCY
        {
            get
            {
                return _InvoiceDiscountAmountLCY;
            }
            set
            {
                if (_InvoiceDiscountAmountLCY != value)
                {
                    this.OnInvoiceDiscountAmountLCYChanging(value);
                    OnPropertyChanging("InvoiceDiscountAmountLCY");
                    _InvoiceDiscountAmountLCY = value;
                    this.OnInvoiceDiscountAmountLCYChanged();
                    OnPropertyChanged("InvoiceDiscountAmountLCY");
                }
            }
        }
        private decimal _InvoiceDiscountAmountLCY;

        [Required()]
        public virtual decimal QtyPerUom
        {
            get
            {
                return _QtyPerUom;
            }
            set
            {
                if (_QtyPerUom != value)
                {
                    this.OnQtyPerUomChanging(value);
                    OnPropertyChanging("QtyPerUom");
                    _QtyPerUom = value;
                    this.OnQtyPerUomChanged();
                    OnPropertyChanged("QtyPerUom");
                }
            }
        }
        private decimal _QtyPerUom;

        [Required()]
        public virtual decimal QuantityBase
        {
            get
            {
                return _QuantityBase;
            }
            set
            {
                if (_QuantityBase != value)
                {
                    this.OnQuantityBaseChanging(value);
                    OnPropertyChanging("QuantityBase");
                    _QuantityBase = value;
                    this.OnQuantityBaseChanged();
                    OnPropertyChanged("QuantityBase");
                }
            }
        }
        private decimal _QuantityBase;

        [Required()]
        public virtual long OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                if (_OrganizationId != value)
                {
                    this.OnOrganizationIdChanging(value);
                    OnPropertyChanging("OrganizationId");
                    _OrganizationId = value;
                    this.OnOrganizationIdChanged();
                    OnPropertyChanged("OrganizationId");
                }
            }
        }
        private long _OrganizationId;

        [Required()]
        public virtual long ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                if (_ClientId != value)
                {
                    this.OnClientIdChanging(value);
                    OnPropertyChanging("ClientId");
                    _ClientId = value;
                    this.OnClientIdChanged();
                    OnPropertyChanged("ClientId");
                }
            }
        }
        private long _ClientId;

        #endregion

        #region Navigation Properties

        public virtual PosHeader PosHeader
        {
            get
            {
                return _PosHeader;
            }
            set
            {
                if (_PosHeader != value)
                {
                    this.OnPosHeaderChanging(value);
                    OnPropertyChanging("PosHeader");
                    _PosHeader = value;
                    this.OnPosHeaderChanged();
                    OnPropertyChanged("PosHeader");
                }
            }
        }
        private PosHeader _PosHeader;
        public virtual SalesPrice SalesPrice
        {
            get
            {
                return _SalesPrice;
            }
            set
            {
                if (_SalesPrice != value)
                {
                    this.OnSalesPriceChanging(value);
                    OnPropertyChanging("SalesPrice");
                    _SalesPrice = value;
                    this.OnSalesPriceChanged();
                    OnPropertyChanged("SalesPrice");
                }
            }
        }
        private SalesPrice _SalesPrice;
        public virtual Location Location
        {
            get
            {
                return _Location;
            }
            set
            {
                if (_Location != value)
                {
                    this.OnLocationChanging(value);
                    OnPropertyChanging("Location");
                    _Location = value;
                    this.OnLocationChanged();
                    OnPropertyChanged("Location");
                }
            }
        }
        private Location _Location;

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        partial void OnPosHeaderIdChanging(long? value);
        partial void OnPosHeaderIdChanged();
        partial void OnLineNoChanging(long value);
        partial void OnLineNoChanged();
        partial void OnTypeChanging(byte value);
        partial void OnTypeChanged();
        partial void OnItemIdChanging(long? value);
        partial void OnItemIdChanged();
        partial void OnLocationIdChanging(long? value);
        partial void OnLocationIdChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnUomIdChanging(long? value);
        partial void OnUomIdChanged();
        partial void OnUomDescriptionChanging(string value);
        partial void OnUomDescriptionChanged();
        partial void OnQuantityChanging(decimal value);
        partial void OnQuantityChanged();
        partial void OnSalesPriceIdChanging(long? value);
        partial void OnSalesPriceIdChanged();
        partial void OnUnitPriceChanging(decimal value);
        partial void OnUnitPriceChanged();
        partial void OnAmountChanging(decimal value);
        partial void OnAmountChanged();
        partial void OnVatIdentifierIdChanging(long? value);
        partial void OnVatIdentifierIdChanged();
        partial void OnVatPercentageChanging(short value);
        partial void OnVatPercentageChanged();
        partial void OnVatAmountChanging(decimal value);
        partial void OnVatAmountChanged();
        partial void OnDiscountIdChanging(long? value);
        partial void OnDiscountIdChanged();
        partial void OnLineDiscountPercentageChanging(byte value);
        partial void OnLineDiscountPercentageChanged();
        partial void OnLineDiscountAmountChanging(decimal value);
        partial void OnLineDiscountAmountChanged();
        partial void OnInvoiceDiscountAmountChanging(decimal value);
        partial void OnInvoiceDiscountAmountChanged();
        partial void OnUnitPriceLCYChanging(decimal value);
        partial void OnUnitPriceLCYChanged();
        partial void OnAmountLCYChanging(decimal value);
        partial void OnAmountLCYChanged();
        partial void OnVatAmountLCYChanging(decimal value);
        partial void OnVatAmountLCYChanged();
        partial void OnLineDiscountAmountLCYChanging(decimal value);
        partial void OnLineDiscountAmountLCYChanged();
        partial void OnInvoiceDiscountAmountLCYChanging(decimal value);
        partial void OnInvoiceDiscountAmountLCYChanged();
        partial void OnQtyPerUomChanging(decimal value);
        partial void OnQtyPerUomChanged();
        partial void OnQuantityBaseChanging(decimal value);
        partial void OnQuantityBaseChanged();
        partial void OnOrganizationIdChanging(long value);
        partial void OnOrganizationIdChanged();
        partial void OnClientIdChanging(long value);
        partial void OnClientIdChanged();
        partial void OnPosHeaderChanging(PosHeader value);
        partial void OnPosHeaderChanged();
        partial void OnSalesPriceChanging(SalesPrice value);
        partial void OnSalesPriceChanged();
        partial void OnLocationChanging(Location value);
        partial void OnLocationChanged();

        #endregion

        #region INotifyPropertyChanging Members

        public event PropertyChangingEventHandler PropertyChanging;

        protected void OnPropertyChanging(string propertyName) {

          if (PropertyChanging != null)
            PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
        }

        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
