// Code is generated by Telerik Data Access Service Wizard
// using WebApiRepositories.tt template

namespace MyERP.Web
{
    public partial class ClientRepository : BaseRepository<MyERP.DataAccess.Client, MyERP.DataAccess.EntitiesModel>
    {

    }


    public partial class CurrencyRepository : BaseRepository<MyERP.DataAccess.Currency, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class OrganizationRepository : BaseRepository<MyERP.DataAccess.Organization, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class UserRepository : BaseRepository<MyERP.DataAccess.User, MyERP.DataAccess.EntitiesModel>
    {
	
    }

    public partial class RoleRepository : BaseRepository<MyERP.DataAccess.Role, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class NoSequenceRepository : BaseRepository<MyERP.DataAccess.NoSequence, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class NoSequenceLineRepository : BaseRepository<MyERP.DataAccess.NoSequenceLine, MyERP.DataAccess.EntitiesModel>
    {

    }
    public partial class OptionRepository : BaseRepository<MyERP.DataAccess.Option, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class UomRepository : BaseRepository<MyERP.DataAccess.Uom, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class ItemRepository : BaseRepository<MyERP.DataAccess.Item, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class ItemGroupRepository : BaseRepository<MyERP.DataAccess.ItemGroup, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class ItemUomRepository : BaseRepository<MyERP.DataAccess.ItemUom, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class LocationRepository : BaseRepository<MyERP.DataAccess.Location, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class BusinessPartnerRepository : BaseRepository<MyERP.DataAccess.BusinessPartner, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class BusinessPartnerGroupRepository : BaseRepository<MyERP.DataAccess.BusinessPartnerGroup, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class BusinessPartnerPriceGroupRepository : BaseRepository<MyERP.DataAccess.BusinessPartnerPriceGroup, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class SalesPriceGroupRepository : BaseRepository<MyERP.DataAccess.SalesPriceGroup, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class SalesPriceRepository : BaseRepository<MyERP.DataAccess.SalesPrice, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class PosHeaderRepository : BaseRepository<MyERP.DataAccess.PosHeader, MyERP.DataAccess.EntitiesModel>
    {

    }

    public partial class PosLineRepository : BaseRepository<MyERP.DataAccess.PosLine, MyERP.DataAccess.EntitiesModel>
    {

    }
}
