#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MyERP.DataAccess;

namespace MyERP.DataAccess	
{
	public partial class Client
	{
		private Guid _clientId;
		public virtual Guid ClientId
		{
			get
			{
				return this._clientId;
			}
			set
			{
				this._clientId = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private long _version;
		public virtual long Version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
		
		private bool _isActivated;
		public virtual bool IsActivated
		{
			get
			{
				return this._isActivated;
			}
			set
			{
				this._isActivated = value;
			}
		}
		
		private Guid _recCreatedById;
		public virtual Guid RecCreatedById
		{
			get
			{
				return this._recCreatedById;
			}
			set
			{
				this._recCreatedById = value;
			}
		}
		
		private DateTime _recCreated;
		public virtual DateTime RecCreated
		{
			get
			{
				return this._recCreated;
			}
			set
			{
				this._recCreated = value;
			}
		}
		
		private string _cultureId;
		public virtual string CultureId
		{
			get
			{
				return this._cultureId;
			}
			set
			{
				this._cultureId = value;
			}
		}
		
		private short _amountDecimalPlaces;
		public virtual short AmountDecimalPlaces
		{
			get
			{
				return this._amountDecimalPlaces;
			}
			set
			{
				this._amountDecimalPlaces = value;
			}
		}
		
		private decimal _amountRoundingPrecision;
		public virtual decimal AmountRoundingPrecision
		{
			get
			{
				return this._amountRoundingPrecision;
			}
			set
			{
				this._amountRoundingPrecision = value;
			}
		}
		
		private short _unitAmountDecimalPlaces;
		public virtual short UnitAmountDecimalPlaces
		{
			get
			{
				return this._unitAmountDecimalPlaces;
			}
			set
			{
				this._unitAmountDecimalPlaces = value;
			}
		}
		
		private decimal _unitAmountRoundingPrecision;
		public virtual decimal UnitAmountRoundingPrecision
		{
			get
			{
				return this._unitAmountRoundingPrecision;
			}
			set
			{
				this._unitAmountRoundingPrecision = value;
			}
		}
		
		private Guid _currencyLCYId;
		public virtual Guid CurrencyLCYId
		{
			get
			{
				return this._currencyLCYId;
			}
			set
			{
				this._currencyLCYId = value;
			}
		}
		
		private DateTime _recModified;
		public virtual DateTime RecModified
		{
			get
			{
				return this._recModified;
			}
			set
			{
				this._recModified = value;
			}
		}
		
		private Guid _recModifiedById;
		public virtual Guid RecModifiedById
		{
			get
			{
				return this._recModifiedById;
			}
			set
			{
				this._recModifiedById = value;
			}
		}
		
		private User _user;
		public virtual User RecCreatedByUser
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		
		private User _user1;
		public virtual User RecModifiedByUser
		{
			get
			{
				return this._user1;
			}
			set
			{
				this._user1 = value;
			}
		}
		
		private Currency _currencyLCY;
		public virtual Currency CurrencyLCY
		{
			get
			{
				return this._currencyLCY;
			}
			set
			{
				this._currencyLCY = value;
			}
		}
		
		private IList<Organization> _organization = new List<Organization>();
		public virtual IList<Organization> Organizations
		{
			get
			{
				return this._organization;
			}
		}
		
	}
}
#pragma warning restore 1591
