//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 11/03/2021 3:16:01 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace MyERP.DataAccess
{
    public partial class Report
    {

        public Report()
        {
            OnCreated();
        }

        #region Properties

        [Key]
        [Required()]
        public virtual long Id { get; set; }

        [StringLength(256)]
        [Required()]
        public virtual string RepId { get; set; }

        [StringLength(3)]
        [Required()]
        public virtual string RepNo { get; set; }

        [StringLength(256)]
        [Required()]
        public virtual string Text { get; set; }

        [StringLength(256)]
        [Required()]
        public virtual string Title { get; set; }

        [StringLength(256)]
        public virtual string FileName { get; set; }

        public virtual string Blob { get; set; }

        #endregion

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
